name: shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, world!"
      - name: multiline script
        run: |
          node -v
          npm -v

      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python #this line tell action to run python in python sell instead of bast

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash 

