name: Your Workflow Name

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables for dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo ${{ secrets.DEV_ENV_VARS }} >> .env.json

      - name: Set environment variables for main branch
        if: github.ref == 'refs/heads/main'
        run: echo ${{ secrets.PROD_ENV_VARS }} >> .env.json

      - name: Parse environment variables
        run: |
          envVars=$(cat .env.json)
          for key in $(echo $envVars | jq -r "keys[]"); do
            value=$(echo $envVars | jq -r .$key)
            echo "$key=$value" >> .env
          done

 